name: Generate Flamoji JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BASE_URL: ${{ vars.FLAMOJI_BASE_URL || '/assets/emojis' }}

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate flamoji JSON files
        run: |
          python3 generate_flamoji.py --base-url "$BASE_URL"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add collections/*/flamoji.json
          git commit -m "Update flamoji.json files"
          git push
