name: Upload Emojis to RocketChat

on:
  workflow_dispatch:
    inputs:
      collection:
        description: 'Collection to upload (leave empty to upload all)'
        required: false
        type: string

env:
  ROCKETCHAT_SERVER_URL: ${{ secrets.ROCKETCHAT_SERVER_URL }}
  ADMIN_USERNAME: ${{ secrets.ROCKETCHAT_ADMIN_USERNAME }}
  ADMIN_PASSWORD: ${{ secrets.ROCKETCHAT_ADMIN_PASSWORD }}

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clone rocketchat-emoji-bulk-upload
        run: |
          git clone https://github.com/anefzaoui/rocketchat-emoji-bulk-upload.git
          cd rocketchat-emoji-bulk-upload
          npm install

      - name: Create .env file
        run: |
          cd rocketchat-emoji-bulk-upload
          cat > .env << EOF
          ROCKETCHAT_SERVER_URL=${{ secrets.ROCKETCHAT_SERVER_URL }}
          ADMIN_USERNAME=${{ secrets.ROCKETCHAT_ADMIN_USERNAME }}
          ADMIN_PASSWORD=${{ secrets.ROCKETCHAT_ADMIN_PASSWORD }}
          EOF

      - name: Upload specific collection
        if: ${{ github.event.inputs.collection != '' }}
        run: |
          cd rocketchat-emoji-bulk-upload
          YAML_FILE="${GITHUB_WORKSPACE}/collections/${{ github.event.inputs.collection }}/rocketchat.yaml"
          if [ -f "$YAML_FILE" ]; then
            echo "Uploading collection: ${{ github.event.inputs.collection }}"
            node import-custom-emojis.js "$YAML_FILE"
          else
            echo "Error: Collection ${{ github.event.inputs.collection }} not found"
            exit 1
          fi

      - name: Upload all collections
        if: ${{ github.event.inputs.collection == '' }}
        run: |
          cd rocketchat-emoji-bulk-upload
          for yaml_file in ${GITHUB_WORKSPACE}/collections/*/rocketchat.yaml; do
            if [ -f "$yaml_file" ]; then
              collection=$(basename $(dirname "$yaml_file"))
              echo "Uploading collection: $collection"
              node import-custom-emojis.js "$yaml_file"
            fi
          done
